all: ArrayList.o Point.o
	        gcc -g ArrayList.o Point.o PointListMain.c -o PointListMain 

ArrayList.o: ArrayList.c ArrayList.h
	        gcc -c ArrayList.c ArrayList.h

Point.o: Point.c Point.h
	        gcc -c Point.c Point.h
