all: ArrayList.o NameCard.o
	        gcc -g ArrayList.o NameCard.o NameCardMain.c -o NameCardMain 

ArrayList.o: ArrayList.c ArrayList.h
	        gcc -c ArrayList.c ArrayList.h

NameCard.o: NameCard.c NameCard.h
	        gcc -c NameCard.c NameCard.h
